require: 
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - bin/bundle

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 9

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4